// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8-N4g_1zDyvsBgs8C43DlCMT-fwcFTU8',
    appId: '1:900437017520:android:6d168dfc342961e8f70c75',
    messagingSenderId: '900437017520',
    projectId: 'quantum-88bef',
    storageBucket: 'quantum-88bef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpq_PBxfm7Kqc4OAlUDgkYgR0cETxOsZk',
    appId: '1:900437017520:ios:b7ac79b8631347def70c75',
    messagingSenderId: '900437017520',
    projectId: 'quantum-88bef',
    storageBucket: 'quantum-88bef.appspot.com',
    androidClientId: '900437017520-92v9q37qroine6dgk1mpk6l1rakempht.apps.googleusercontent.com',
    iosClientId: '900437017520-deos7q9q1m7aq6snns8u6432lhkaevpl.apps.googleusercontent.com',
    iosBundleId: 'com.quantum.admin',
  );
}
